apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: myapp
    type: frontend
  type: NodePort                      # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
#   namespace: default
# spec:
#   ports:
#   - nodePort: 30080
#     port: 8080
#     targetPort: 8080
#   selector:
#     name: simple-webapp
#   type: NodePort