apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: myapp
    #env: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
  
