apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: alpine:latest
    command: [ 'sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done' ]
    volumeMounts:
    - name: data
      mountPath: /opt
    resources:
      requests:
        memory: "64Mi"
        cpu: 1
      limits:
        memory: "128Mi"
        cpu: 2
  initContainers:
  - name: log-shipper
    image: alpine:latest
    command: [ 'sh', '-c', 'tail -F /opt/logs.txt' ]
    volumeMounts:
    - name: data
      mountPath: /opt
    resources:
      requests:
        memory: "64Mi"
        cpu: 1
      limits:
        memory: "128Mi"
        cpu: 2
  restartPolicy: Always
  volumes:
  - name: data
    emptyDir: {}
