apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  #restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: nginx
    image: nginx

