apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
        type: frontend
    spec:
      #restartPolicy: Always            # Always, OnFailure, Never
      containers:
      - name: nginx
        image: nginx
  replicas: 3